### PR TITLE
Write the crypt/decrypt algo with a basic test in main

### PR DESCRIPTION
**Pull request by AnisMessaoudi**
If you can test it with others files/examples and give me a feedback. :)

### CODE REVIEW

**Comment by thenjip** [comment]
Your text resource is missing. You can put it in 'src/main/resources/txt/'.

**Comment by AnisMessaoudi** [comment]
I can't reach resources if they are not in root's project. And should not the programm create the file if they doesn't exist ?

**Comment by thenjip** [comment]
Maven adds everything under src/main/resources in the classpath.
So if you want to make the test run, you must use Maven (in command line).
I found a plugin that can help you with that. Let me set it up for you and we'll see.

**Comment by thenjip** [comment]
So, now, if you want to run the main in PartialFileCrypter, you run this command line:
`mvn exec:java`

**Comment by AnisMessaoudi** [comment]
I correct a few things but there is still a problem I can't handle on printFileContent function : the first file is always print correctly but then nothing but this : "[0m[0m"  .
Anyway, the encrypt/decrypt functions are working but I'm still wondering on how use the nonce properly.

**Comment by thenjip** [comment]
So it works now. Great !
As for the printing problem, well, I renamed the file extension '.bytes' because it is not text in the code, just an array of bytes (rather small integers). The printFileContent() should work though since it only displays integers separated by spaces.

Also, when I mean "by blocks", I mean "not loading the whole file in memory". i was not talking about the clear/encrypted parts.
Yeah, sorry if you misunderstood that one.

**Comment by thenjip** [comment]
After your last commit (just above), I manage to run the PartialFileCrypter main function. And it works !
I made a few improvements and refactoring, but the result should be the same.
I fixed printing the file content. We actually ended up closing stdout before.

**Pull request merged**
